services:

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: employee_evaluation_db
      POSTGRES_USER: bishal
      POSTGRES_PASSWORD: shrestha
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bishal -d employee_evaluation_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  employee-evaluation-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/employee_evaluation_db
      QUARKUS_DATASOURCE_USERNAME: bishal
      QUARKUS_DATASOURCE_PASSWORD: shrestha
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

volumes:
  postgres_data:
